name: Sanity Test 
on: 
  workflow_dispatch: 
permissions: 
  contents: write 
  pull-requests: write 
jobs: 
  test_model:
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v4
        with: 
          python-version: "3.9"
      - name: CML Setup 
        uses: iterative/setup-cml@v2
      - name: Run Unit Tests 
        run: |
          pip install -r week4/requirements.txt
          pip install dvc
          python3 week4/test.py > test_output.txt 
      - name: CML Report 
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Test Output" >> report.md
          echo "------" >> report.md
          cat test_output.txt >> report.md
          echo "------" >> report.md
          echo "Predictions on v2 from training on v1" >> report.md
          cat w2_w4Integrated/outputs/v2/predictions.csv >> repord.md 
          cml comment create --publish report.md
